spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  simulator:
    topic: shipment-events

simulator:
  logistics:
    anomaly-rates:
      temperature: 0.05
      route-deviation: 0.02
    delays-ms:
      loading: 15000
      driving: 30000
      unloading: 20000
